const $=s=>document.querySelector(s);let L;
const lower=s=>(s||'').toLowerCase();
function setHead(){let h=L.human_review_card||{};$('#title').textContent=L.name;$('#hook').textContent=h.one_sentence||L.hook;$('#stats').innerHTML=`<div>#${String(L.n).padStart(3,'0')}</div><div>${h.plain_title||L.name}</div>`}
function log(t){$('#log').innerHTML='<div>• '+t+'</div>'+$('#log').innerHTML}
function resetUI(){setHead();$('#stage').innerHTML='';$('#choices').innerHTML='';$('#log').innerHTML=''}
function b(t,fn,c='choice'){let x=document.createElement('button');x.className=c;x.innerHTML=`<h3>${t}</h3>`;x.onclick=fn;$('#choices').appendChild(x);return x}
function result(title,txt){$('#choices').innerHTML='';$('#stage').insertAdjacentHTML('beforeend',`<div class="result">${title}</div><p class="paper">${txt}</p>`);b('다시 하기',start,'choice primary');b('목록으로',()=>location.href='ideas200.html')}
function drawTrace(marked=false,control=false){let c=$('#viz'),x=c.getContext('2d'),w=c.width,h=c.height;x.fillStyle='#03060c';x.fillRect(0,0,w,h);x.strokeStyle='#2f3a55';x.strokeRect(8,8,w-16,h-16);x.fillStyle='#d8e6ff';x.font='16px system-ui';x.fillText('Calcium trace: MB247 > GCaMP, blue-light assay',18,28);x.strokeStyle='#7cc7ff';x.lineWidth=3;x.beginPath();for(let i=0;i<90;i++){let px=25+i*(w-50)/89, py=170+Math.sin(i*.28)*18; if(i>45&&i<56)py-=70*Math.sin((i-45)/11*Math.PI); if(i==0)x.moveTo(px,py); else x.lineTo(px,py)}x.stroke();if(marked){x.fillStyle='rgba(245,200,106,.22)';x.fillRect(w*.48,75,90,145);x.fillStyle='#f5c86a';x.fillText('suspicious spike',w*.48,70)}if(control){x.strokeStyle='#b7f56f';x.lineWidth=2;x.beginPath();for(let i=0;i<90;i++){let px=25+i*(w-50)/89, py=230+Math.sin(i*.28)*10; if(i==0)x.moveTo(px,py); else x.lineTo(px,py)}x.stroke();x.fillStyle='#b7f56f';x.fillText('heat-control trace: no spike',18,255)}}
function proper001(){resetUI();let found={spike:false,vial:false,control:false};let submitted=false;$('#stage').innerHTML=`<div class="kicker">BESPOKE PROTOTYPE #001</div><h2>Data Ghost Detective</h2><p class="body"><b>아이디어:</b> 칼슘 trace에 나타난 불가능한 spike가 진짜 초파리 행동인지, 장비 artifact인지 추리하는 3분 탐정 게임.</p><div class="objective"><b>해야 하는 것</b><br>1. trace에서 이상 구간을 표시한다.<br>2. vial label과 control trace를 확인한다.<br>3. 원인을 선택해 논문 claim으로 제출한다.</div><div id="case" class="objective"><b>Case:</b> Blue light 자극 직후 모든 파리가 같은 방향으로 도는 듯한 calcium spike가 나타났다. PI는 “hive mind”라고 부르고 싶어 한다.</div>`;drawTrace(false,false);
function update(){let clues=[];if(found.spike)clues.push('Trace spike marked');if(found.vial)clues.push('Vial label mismatch: MB247 crossed with unknown driver');if(found.control)clues.push('Heat-control has no spike');$('#case').innerHTML='<b>Case notes:</b><br>'+(clues.length?clues.map(x=>'• '+x).join('<br>'):'아직 단서 없음. trace부터 보자.');}
function submit(kind){if(submitted)return;submitted=true;let n=Object.values(found).filter(Boolean).length;if(kind==='artifact')result('Artifact caught',`단서 ${n}/3개로 spike가 vial mix-up과 blue-light artifact의 결합임을 밝혔다. 재미는 “유령 신호를 추리로 죽이는 순간”에 있다.`);else if(kind==='phenomenon'&&n>=2)result('Risky publishable phenomenon',`단서 ${n}/3개를 바탕으로 “Light-locked collective turning” claim을 제출했다. 진짜일 수도 있지만 Reviewer #2가 온다.`);else result('Bad claim',`단서가 부족한데 큰 claim을 냈다. 이 프로토타입은 clue→hypothesis→claim 구조가 재미있는지 검증한다.`)}
b('1. Trace spike 표시',()=>{found.spike=true;drawTrace(true,found.control);log('이상 spike 구간을 표시했다.');update()});
b('2. Vial label 확인',()=>{found.vial=true;log('라벨이 이상하다: driver stock이 한 세대 밀렸다.');update()});
b('3. Heat-control 대조',()=>{found.control=true;drawTrace(found.spike,true);log('heat-control에는 spike가 없다.');update()});
b('Artifact로 결론',()=>submit('artifact'),'choice primary');
b('새 현상으로 논문화',()=>submit('phenomenon'),'choice danger');update()}
function drawSwarm(pulses=[],tempo=120,playing=false){let c=$('#viz'),x=c.getContext('2d'),w=c.width,h=c.height,t=0,active=pulses.reduce((a,b)=>a+b,0);function f(){x.fillStyle='#03060c';x.fillRect(0,0,w,h);x.strokeStyle='#2f3a55';x.strokeRect(8,8,w-16,h-16);x.fillStyle='#d8e6ff';x.font='16px system-ui';x.fillText('Optogenetic chamber: pulse rhythm → swarm response',18,28);for(let i=0;i<8;i++){x.fillStyle=pulses[i]?'#f5c86a':'#172033';x.fillRect(35+i*55,45,38,26)}let sync=active>=3&&active<=5;for(let i=0;i<48;i++){let a=(sync?t*.07: t*.025)+i*.52, r=sync?55+(i%5)*8:35+(i%9)*12;let px=w/2+Math.cos(a)*r, py=175+Math.sin(a*(sync?1:1.7))*r*.55;x.fillStyle=sync?'#f5c86a':'#7cc7ff';x.fillRect(px,py,5,5)}x.fillStyle=sync?'#f5c86a':'#b9c7dd';x.fillText(sync?'LOCKED SWARM RHYTHM':'noisy wandering',18,280);if(playing){t++;requestAnimationFrame(f)}}f()}
function proper008(){resetUI();let pulses=Array(8).fill(0),tempo=120,played=false;$('#stage').innerHTML=`<div class="kicker">BESPOKE PROTOTYPE #008</div><h2>Optogenetic Rhythm Lab</h2><p class="body"><b>아이디어:</b> 빛 pulse를 박자처럼 찍어서 파리 군집 움직임을 만드는 리듬 실험 게임.</p><div class="objective"><b>해야 하는 것</b><br>1. 8칸 sequencer에 빛 pulse를 찍는다.<br>2. tempo를 조절한다.<br>3. Play를 눌러 chamber 반응을 보고, 논문 claim으로 저장할지 판단한다.</div><div id="seq" style="display:grid;grid-template-columns:repeat(8,1fr);gap:8px;margin:12px 0"></div><div id="readout" class="objective">Pulse 0/8 · Tempo 120 · 아직 반응 없음</div>`;let seq=$('#seq');function update(){let n=pulses.reduce((a,b)=>a+b,0);$('#readout').innerHTML=`Pulse ${n}/8 · Tempo ${tempo} · ${played?(n>=3&&n<=5?'군집 rhythm lock 감지':'반응이 산만함'):'패턴을 찍고 Play를 누르자'}`;drawSwarm(pulses,tempo,played)}for(let i=0;i<8;i++){let cell=document.createElement('button');cell.className='choice';cell.innerHTML=`<h3>${i+1}</h3>`;cell.onclick=()=>{pulses[i]=1-pulses[i];cell.style.background=pulses[i]?'#3d2f09':'#172033';log(`pulse ${i+1} ${pulses[i]?'ON':'OFF'}`);update()};seq.appendChild(cell)}b('Tempo -',()=>{tempo=Math.max(80,tempo-20);log('tempo down');update()});b('Tempo +',()=>{tempo=Math.min(180,tempo+20);log('tempo up');update()});b('Play chamber',()=>{played=true;let n=pulses.reduce((a,b)=>a+b,0);log(n>=3&&n<=5?'swarm rhythm locked':'flies wandered noisily');update()});b('논문 claim 저장',()=>{let n=pulses.reduce((a,b)=>a+b,0);if(!played)result('No assay','아직 chamber를 재생하지 않았다. pulse를 찍고 Play를 눌러야 한다.');else if(n>=3&&n<=5)result('Light-Induced Swarm Dance','파리들이 pulse rhythm에 맞춰 원형 군무를 시작했다. 이 prototype의 재미는 “내가 찍은 rhythm이 살아있는 행동으로 돌아오는 순간”이다.');else result('Noisy Trace','pulse가 너무 적거나 많아 산만한 움직임만 나왔다. 다시 tempo와 pulse 수를 조절하고 싶게 만드는지 확인하자.')},'choice primary');update()}
function simpleCard(){let h=L.human_review_card||{};return `<div class="kicker">#${String(L.n).padStart(3,'0')}</div><h2>${h.plain_title||L.name}</h2><p class="body"><b>아이디어:</b> ${h.one_sentence||L.hook}</p><div class="objective"><b>핵심 조작</b><br>${(h.actual_player_actions||['선택한다','결과를 본다']).map(x=>'• '+x).join('<br>')}<br><br><b>첫 화면:</b> ${h.screen_model||L.prototype_focus}<br><b>재밌는 순간:</b> ${h.signature_moment||L.player_promise}</div>`}
function generic(){resetUI();$('#stage').innerHTML=simpleCard()+`<h2>Playable sketch</h2><p>아직 전용 구현 전. 핵심 선택만 확인한다.</p>`;drawTrace(false,false);b('정확하게 검증',()=>result('Credible result','느리지만 믿을 만한 결과.'));b('이상함을 키우기',()=>result('Memorable result','이상하고 공유하기 쉬운 결과.'));b('위험한 shortcut',()=>result('Scandal risk','재밌지만 의심스러운 결과.'),'choice danger')}
function start(){if(String(L.id).startsWith('001-'))proper001();else if(String(L.id).startsWith('008-'))proper008();else generic()}
fetch('loops200.json?v=human-readable-v1').then(r=>r.json()).then(d=>{let id=new URLSearchParams(location.search).get('id');L=d.find(x=>x.id===id)||d[0];start()});
