const $=s=>document.querySelector(s);let L;
const lower=s=>(s||'').toLowerCase();
function setHead(){let h=L.human_review_card||{};$('#title').textContent=L.name;$('#hook').textContent=h.one_sentence||L.hook;$('#stats').innerHTML=`<div>#${String(L.n).padStart(3,'0')}</div><div>${h.plain_title||L.name}</div>`}
function log(t){$('#log').innerHTML='<div>• '+t+'</div>'+$('#log').innerHTML}
function resetUI(){setHead();$('#stage').innerHTML='';$('#choices').innerHTML='';$('#log').innerHTML=''}
function b(t,fn,c='choice'){let x=document.createElement('button');x.className=c;x.innerHTML=`<h3>${t}</h3>`;x.onclick=fn;$('#choices').appendChild(x);return x}
function result(title,txt){$('#choices').innerHTML='';$('#stage').insertAdjacentHTML('beforeend',`<div class="result">${title}</div><p class="paper">${txt}</p>`);b('다시 하기',start,'choice primary');b('목록으로',()=>location.href='ideas200.html')}
function drawTrace(marked=false,control=false){let c=$('#viz'),x=c.getContext('2d'),w=c.width,h=c.height;x.fillStyle='#03060c';x.fillRect(0,0,w,h);x.strokeStyle='#2f3a55';x.strokeRect(8,8,w-16,h-16);x.fillStyle='#d8e6ff';x.font='16px system-ui';x.fillText('Calcium trace: MB247 > GCaMP, blue-light assay',18,28);x.strokeStyle='#7cc7ff';x.lineWidth=3;x.beginPath();for(let i=0;i<90;i++){let px=25+i*(w-50)/89, py=170+Math.sin(i*.28)*18; if(i>45&&i<56)py-=70*Math.sin((i-45)/11*Math.PI); if(i==0)x.moveTo(px,py); else x.lineTo(px,py)}x.stroke();if(marked){x.fillStyle='rgba(245,200,106,.22)';x.fillRect(w*.48,75,90,145);x.fillStyle='#f5c86a';x.fillText('suspicious spike',w*.48,70)}if(control){x.strokeStyle='#b7f56f';x.lineWidth=2;x.beginPath();for(let i=0;i<90;i++){let px=25+i*(w-50)/89, py=230+Math.sin(i*.28)*10; if(i==0)x.moveTo(px,py); else x.lineTo(px,py)}x.stroke();x.fillStyle='#b7f56f';x.fillText('heat-control trace: no spike',18,255)}}
function proper001(){resetUI();let found={spike:false,vial:false,control:false};let submitted=false;$('#stage').innerHTML=`<div class="kicker">BESPOKE PROTOTYPE #001</div><h2>Data Ghost Detective</h2><p class="body"><b>아이디어:</b> 칼슘 trace에 나타난 불가능한 spike가 진짜 초파리 행동인지, 장비 artifact인지 추리하는 3분 탐정 게임.</p><div class="objective"><b>해야 하는 것</b><br>1. trace에서 이상 구간을 표시한다.<br>2. vial label과 control trace를 확인한다.<br>3. 원인을 선택해 논문 claim으로 제출한다.</div><div id="case" class="objective"><b>Case:</b> Blue light 자극 직후 모든 파리가 같은 방향으로 도는 듯한 calcium spike가 나타났다. PI는 “hive mind”라고 부르고 싶어 한다.</div>`;drawTrace(false,false);
function update(){let clues=[];if(found.spike)clues.push('Trace spike marked');if(found.vial)clues.push('Vial label mismatch: MB247 crossed with unknown driver');if(found.control)clues.push('Heat-control has no spike');$('#case').innerHTML='<b>Case notes:</b><br>'+(clues.length?clues.map(x=>'• '+x).join('<br>'):'아직 단서 없음. trace부터 보자.');}
function submit(kind){if(submitted)return;submitted=true;let n=Object.values(found).filter(Boolean).length;if(kind==='artifact')result('Artifact caught',`단서 ${n}/3개로 spike가 vial mix-up과 blue-light artifact의 결합임을 밝혔다. 재미는 “유령 신호를 추리로 죽이는 순간”에 있다.`);else if(kind==='phenomenon'&&n>=2)result('Risky publishable phenomenon',`단서 ${n}/3개를 바탕으로 “Light-locked collective turning” claim을 제출했다. 진짜일 수도 있지만 Reviewer #2가 온다.`);else result('Bad claim',`단서가 부족한데 큰 claim을 냈다. 이 프로토타입은 clue→hypothesis→claim 구조가 재미있는지 검증한다.`)}
b('1. Trace spike 표시',()=>{found.spike=true;drawTrace(true,found.control);log('이상 spike 구간을 표시했다.');update()});
b('2. Vial label 확인',()=>{found.vial=true;log('라벨이 이상하다: driver stock이 한 세대 밀렸다.');update()});
b('3. Heat-control 대조',()=>{found.control=true;drawTrace(found.spike,true);log('heat-control에는 spike가 없다.');update()});
b('Artifact로 결론',()=>submit('artifact'),'choice primary');
b('새 현상으로 논문화',()=>submit('phenomenon'),'choice danger');update()}
function simpleCard(){let h=L.human_review_card||{};return `<div class="kicker">#${String(L.n).padStart(3,'0')}</div><h2>${h.plain_title||L.name}</h2><p class="body"><b>아이디어:</b> ${h.one_sentence||L.hook}</p><div class="objective"><b>핵심 조작</b><br>${(h.actual_player_actions||['선택한다','결과를 본다']).map(x=>'• '+x).join('<br>')}<br><br><b>첫 화면:</b> ${h.screen_model||L.prototype_focus}<br><b>재밌는 순간:</b> ${h.signature_moment||L.player_promise}</div>`}
function generic(){resetUI();$('#stage').innerHTML=simpleCard()+`<h2>Playable sketch</h2><p>아직 전용 구현 전. 핵심 선택만 확인한다.</p>`;drawTrace(false,false);b('정확하게 검증',()=>result('Credible result','느리지만 믿을 만한 결과.'));b('이상함을 키우기',()=>result('Memorable result','이상하고 공유하기 쉬운 결과.'));b('위험한 shortcut',()=>result('Scandal risk','재밌지만 의심스러운 결과.'),'choice danger')}
function start(){if(String(L.id).startsWith('001-'))proper001();else generic()}
fetch('loops200.json?v=human-readable-v1').then(r=>r.json()).then(d=>{let id=new URLSearchParams(location.search).get('id');L=d.find(x=>x.id===id)||d[0];start()});
