const $=s=>document.querySelector(s);let L,S;
function add(o){for(const k of ['ev','weird','cred','hype','susp','score'])S[k]=Math.max(0,Math.min(150,S[k]+(o[k]||0)));log(`${o.label||'choice'}: ${o.effect||''}`)}
function log(t){S.log.push('• '+t)}
function stats(){ $('#stats').innerHTML=`<div>#${String(L.n).padStart(3,'0')}</div><div>${L.axis}</div><div>Score ${S.score}</div><div>Evidence ${S.ev}</div><div>Weird ${S.weird}</div><div>Cred ${S.cred}</div><div>Hype ${S.hype}</div><div>Susp ${S.susp}</div>`; $('#log').innerHTML=[`<div><b>Motivation:</b> ${L.motive}</div>`,`<div><b>Test:</b> ${L.test}</div>`].concat(S.log.slice(-8).map(x=>`<div>${x}</div>`)).join('')}
function stage(h){$('#stage').innerHTML=h;$('#choices').innerHTML='';stats()}function btn(t,d,fn,c='choice'){let b=document.createElement('button');b.className=c;b.innerHTML=`<h3>${t}</h3><p>${d}</p>`;b.onclick=fn;$('#choices').appendChild(b)}
function meters(){return ['ev','weird','cred','hype','susp'].map(k=>`<div class="meter"><b>${k}</b><span>${S[k]}</span></div>`).join('')}
function start(){S={ev:20,weird:30,cred:35,hype:20,susp:10,score:0,log:[]};$('#title').textContent=L.name;$('#hook').textContent=L.hook;log('Loaded '+L.name);stage(`<div class="kicker">${L.axis} loop candidate</div><h2>${L.name}</h2><div class="objective"><b>Motivation hypothesis:</b> ${L.motive}<br><b>Judge this:</b> ${L.test}</div><p class="body">Setting: <b>${L.setting}</b><br>Phenomenon: <b>${L.phenomenon}</b></p>`);btn(L.a.label,L.a.effect,()=>{add({...L.a,label:L.a.label});mid('careful')});btn(L.b.label,L.b.effect,()=>{add({...L.b,label:L.b.label});mid('aggressive')});btn(L.c.label,L.c.effect,()=>{add({...L.c,label:L.c.label});mid('risky')},'choice danger')}
function mid(path){stage(`<div class="kicker">Consequence</div><h2>${path==='careful'?'Credible but quieter':path==='aggressive'?'Exciting but exposed':'High-risk breakthrough attempt'}</h2><div class="meters">${meters()}</div><p class="body">Now choose what the second beat of this loop should reward.</p>`);btn('Lean into evidence','Convert the run into competence/mastery payoff.',()=>{add({ev:25,cred:15,label:'Evidence payoff'});end('METHODS SURVIVE REVIEW')});btn('Lean into spectacle','Convert the run into curiosity/hype payoff.',()=>{add({weird:20,hype:30,susp:10,label:'Spectacle payoff'});end('MEMORABLE LAB STORY')});btn('Lean into consequence','Convert the run into risk/recovery payoff.',()=>{add({score:25,susp:25,label:'Consequence payoff'});end('DANGEROUSLY INTERESTING')},'choice danger')}
function end(title){S.score=Math.round(S.ev*.2+S.weird*.2+S.cred*.2+S.hype*.25-S.susp*.25+S.score);stage(`<div class="kicker">Result</div><div class="result">${title}</div><p class="paper">${L.name}: ${L.phenomenon} under ${L.setting}</p><div class="objective"><b>Motivation hypothesis:</b> ${L.motive}<br><b>Judge this:</b> ${L.test}</div><div class="meters">${meters()}</div><p class="body"><b>Loop score: ${S.score}</b><br>If this made you want a different second run, mark it as promising.</p>`);btn('Restart idea','Replay this candidate.',start,'choice primary');btn('Back to 200 ideas','Return to index.',()=>location.href='ideas200.html')}
function draw(){const c=$('#viz'),x=c.getContext('2d');let t=0;function f(){t+=.03;x.fillStyle='#02040a';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#26324a';x.strokeRect(8,8,c.width-16,c.height-16);for(let i=0;i<44;i++){let a=t*2+i*.5,r=35+(i%10)*11,px=c.width/2+Math.cos(a+i)*r,py=c.height/2+Math.sin(a*1.1+i)*r*.55;x.fillStyle=i%4?'#f1d35e':'#72bdff';x.fillRect(px,py,6,6)}x.fillStyle='#d8e6ff';x.font='15px system-ui';x.fillText(L?`#${L.n} ${L.axis}`:'loading',18,c.height-20);requestAnimationFrame(f)}f()}
fetch('loops200.json').then(r=>r.json()).then(d=>{let id=new URLSearchParams(location.search).get('id');L=d.find(x=>x.id===id)||d[0];start();draw()});