const q=new URLSearchParams(location.search);const loop=LOOPS.find(x=>x.id===q.get('id'))||LOOPS[0];
let S={step:0,score:0,ev:20,weird:30,cred:35,hype:20,susp:10,time:180,log:[],picked:[],mode:loop.mode};
const $=s=>document.querySelector(s); $('#title').textContent=loop.name; $('#hook').textContent=loop.hook;
function L(t){S.log.push('• '+t)}function add(o){for(const k of ['ev','weird','cred','hype','susp','score','time'])S[k]=Math.max(0,Math.min(k==='time'?300:140,S[k]+(o[k]||0)));if(o.log)L(o.log)}
function stats(){ $('#stats').innerHTML=`<div>Time ${S.time}</div><div>Score ${S.score}</div><div>Risk ${S.susp}</div><div>Evidence ${S.ev}</div><div>Weird ${S.weird}</div><div>Cred ${S.cred}</div><div>Hype ${S.hype}</div>`; $('#log').innerHTML=S.log.slice(-10).map(x=>`<div>${x}</div>`).join('')}
function stage(h){$('#stage').innerHTML=h;$('#choices').innerHTML='';stats()}function b(t,d,fn,c='choice'){let x=document.createElement('button');x.className=c;x.innerHTML=`<h3>${t}</h3><p>${d}</p>`;x.onclick=fn;$('#choices').appendChild(x)}
function meters(){return ['ev','weird','cred','hype','susp'].map(k=>`<div class="meter"><b>${k}</b><span>${S[k]}</span></div>`).join('')}
function end(title,body){S.score=Math.round(S.ev*.2+S.weird*.2+S.cred*.2+S.hype*.25-S.susp*.25);stage(`<div class="kicker">Result</div><div class="result">${title}</div><p class="paper">${body}</p><div class="meters">${meters()}</div><p class="body"><b>Loop score: ${S.score}</b><br>Playtest note: would you try a different strategy?</p>`);b('Restart this candidate','Run the loop again.',()=>location.reload(),'choice primary')}
function init(){L('Candidate loaded: '+loop.name); ({discover,catalog,reviewer,figure,spread,survival,sandbox,economy,rogue,deck,roulette,automation,email,arcade,claim})[S.mode](); draw()}function discover(){stage(`<div class="kicker">Trait Discovery</div><h2>Pick 3 traits to discover a behavior</h2><p class="body">Core: 조합 → 예상 밖 현상 → 논문 포장.</p>`); b('Quick test: Blue Light + Hyperactive + Social','Immediately test the intended first-run combo.',()=>{S.picked=['Blue Light','Hyperactive Motor','Social Bias'];add({weird:45,hype:25,ev:15,log:'Discovered '+PHENOMENA[0]});discover2()},'choice primary'); TRAITS.forEach(t=>b((S.picked.includes(t)?'✓ ':'+ ')+t,'Select trait',()=>{if(S.picked.includes(t))S.picked=S.picked.filter(x=>x!==t);else if(S.picked.length<3)S.picked.push(t); if(S.picked.length===3){add({weird:45,hype:25,ev:15,log:'Discovered '+PHENOMENA[0]}); discover2()}else discover()},S.picked.includes(t)?'card selected':'card'))}
function discover2(){stage(`<div class="kicker">Discovered</div><div class="result">${PHENOMENA[0]}</div><p class="body">The flies circle under blue light. Is it rigorous or just weird?</p><div class="meters">${meters()}</div>`);b('Careful control','Cred +30, Hype -5, Time -40',()=>{add({cred:30,hype:-5,time:-40,log:'Control added'});discover3()});b('Flashy recording','Hype +35, Susp +15',()=>{add({hype:35,susp:15,log:'Recording goes viral in lab Slack'});discover3()})}
function discover3(){stage(`<h2>Frame the finding</h2><div class="meters">${meters()}</div>`);b('Conservative paper','Safe but less exciting',()=>end('SOLID PAPER','Accepted, but no one screenshots it.'));b('Big claim','High upside, higher suspicion',()=>{add({hype:30,weird:10,susp:25});end('VIRAL PREPRINT','Three labs try to replicate it. None use the same flies.')},'choice danger')}
function catalog(){stage(`<div class="kicker">Catalog Hunt</div><h2>Fill the phenomenon catalog</h2><p class="body">Pick a hint slot and chase unknown behavior.</p>`);PHENOMENA.forEach((p,i)=>b(i?'??? Phenomenon '+(i+1):'✓ '+p,i?'Hint: needs '+['light+social','memory+swarm','sleep+wall','courtship+light','sugar+anxiety'][i-1]:'Already found',()=>{add({weird:25,hype:15,score:10,log:'Catalog clue pursued'});end('CATALOG UPDATED',i?`New entry revealed: ${p}`:'You optimized the known first discovery.')}))}
function reviewer(){stage(`<div class="kicker">Reviewer Boss</div><h2>Reviewer #2 prepares an attack</h2><p class="body">Your claim is strong but vulnerable. Choose a defense.</p><div class="meters">${meters()}</div>`);b('Add control','Counters sample-size/control attack. Cred +35, Time -45',()=>{add({cred:35,ev:20,time:-45,log:'Control included'});reviewer2()});b('Add model diagram','Counters mechanism attack. Hype +15, Susp +10',()=>{add({hype:15,susp:10,log:'Diagram arrows added'});reviewer2()});b('Weaken title','Cred +25, Hype -20, Susp -10',()=>{add({cred:25,hype:-20,susp:-10,log:'Title weakened'});reviewer2()})}
function reviewer2(){end(S.cred>S.susp+25?'REVIEW SURVIVED':'MAJOR REVISION',S.cred>S.susp+25?'Reviewer #2 is annoyed but cornered.':'Reviewer #2 requests a second species.')}
function figure(){stage(`<div class="kicker">Figure Puzzle</div><h2>Turn raw chaos into Figure 1</h2><p class="body">Choose how to visualize the same ambiguous data.</p>`);b('Scatterplot with all points','Cred +25, Hype +5',()=>{add({cred:25,hype:5,ev:15});end('HONEST FIGURE','The graph looks boring but defensible.')});b('Beautiful smoothed trace','Hype +35, Susp +20',()=>{add({hype:35,susp:20});end('BEAUTIFUL BUT VAGUE','Everyone likes the figure. Nobody understands it.')});b('Outlier exclusion','Evidence +20, Susp +35',()=>{add({ev:20,susp:35});end('SUSPICIOUSLY CLEAN','The figure sings. The methods whisper.')} ,'choice danger')}
function spread(){stage(`<div class="kicker">Spread Map</div><h2>Let the behavior/hype spread</h2><p class="body">Plague Inc. style: stay credible while spreading through lab, Twitter, and journals.</p>`);b('Quiet replication','Evidence +30, Spread slow',()=>{add({ev:30,cred:20,hype:5,time:-35,log:'Two labs replicate quietly'});spread2()});b('Preprint blast','Hype +45, Susp +25',()=>{add({hype:45,susp:25,weird:10,log:'Preprint spreads'});spread2()});b('Conference demo','Hype +25, Cred +10, Time -25',()=>{add({hype:25,cred:10,time:-25,log:'Conference audience gasps'});spread2()})}
function spread2(){end(S.hype>70&&S.susp<55?'FIELDWIDE PHENOMENON':'CONTAINED ODDITY',S.hype>70?'The behavior spreads through citation networks.':'The result remains a lab legend.')}
function survival(){stage(`<div class="kicker">Lab Survival</div><h2>Publish before the lab collapses</h2><p class="body">Choose which disaster to handle first.</p>`);b('Discard contaminated vials','Evidence -10, Susp -20, Time -30',()=>{add({ev:-10,susp:-20,time:-30,cred:15,log:'Contamination contained'});survival2()});b('Ignore escaped flies','Time saved, Susp +25, Hype +10',()=>{add({susp:25,hype:10,log:'Flies enter coffee machine'});survival2()});b('Ask PI for extension','Time +40, Cred -10, Hype -10',()=>{add({time:40,cred:-10,hype:-10,log:'PI says this is preliminary'});survival2()})}
function survival2(){end(S.susp<45?'LAB BARELY SURVIVES':'LAB ECOLOGY COLLAPSES',S.susp<45?'A figure is submitted from the rubble.':'The stock room becomes an ecosystem argument against your thesis.')}
function sandbox(){stage(`<div class="kicker">Behavior Sandbox</div><h2>Stimulate the chamber</h2><p class="body">The reward is watching weird behavior emerge.</p>`);b('Pulse blue light','Swarm dance visual, Weird +30',()=>{add({weird:30,hype:15,log:'Blue pulse triggers circular swarm'});sandbox2('Swarm Dance')});b('Drop sugar spot','Foraging spiral, Evidence +15',()=>{add({ev:15,weird:25,log:'Sugar spot becomes pilgrimage site'});sandbox2('Foraging Spiral')});b('Switch day/night','Wall parade, Weird +20',()=>{add({weird:20,cred:10,log:'Night cycle reversed'});sandbox2('Wall Parade')})}
function sandbox2(name){end('OBSERVED: '+name,'Sandbox works if watching the chamber is intrinsically funny enough.')}
function economy(){stage(`<div class="kicker">Grant Hype Economy</div><h2>Convert attention into funding</h2>`);b('Respectable grant application','Budget +40, Cred +20, Hype -5',()=>{add({cred:20,hype:-5,score:20,log:'Grant panel nods'});economy2()});b('Viral preprint thread','Budget +60, Hype +35, Susp +25',()=>{add({hype:35,susp:25,score:35,log:'Funding arrives with suspicion'});economy2()});b('Promise impossible assay','Budget +80, Susp +45',()=>{add({susp:45,score:45,log:'You promised too much'});economy2()},'choice danger')}
function economy2(){end(S.susp<60?'FUNDED LAB':'SCANDAL-FUNDED LAB',S.susp<60?'Funding unlocks better experiments.':'Money arrives before reproducibility does.')}
function rogue(){stage(`<div class="kicker">Roguelite Run</div><h2>Random day, random disaster</h2><p class="body">Modifier: Reviewer hates light experiments. Deadline: 3 minutes.</p>`);b('Build around memory trait','Avoids modifier, lower hype',()=>{add({cred:25,ev:20,hype:5});end('CLEAN RUN','A modest but survivable paper.')});b('Force light experiment anyway','High weirdness, modifier risk',()=>{add({weird:55,hype:30,susp:30});end('HIGH VARIANCE RUN','You found a stronger story and a stronger enemy.')});b('Take cursed event card','Big score, big risk',()=>{add({score:50,susp:50,weird:30});end('CURSED RUN','The run is memorable even when it fails.')},'choice danger')}
function deck(){stage(`<div class="kicker">Stock Deckbuilder</div><h2>Draft a publication deck</h2>`);b('Draft Brain Driver','Combo engine. Cred +15',()=>{add({cred:15,log:'Brain Driver drafted'});deck2()});b('Draft Flashy Assay','Hype card. Hype +25',()=>{add({hype:25,log:'Flashy Assay drafted'});deck2()});b('Draft Reviewer Shield','Defense card. Susp -15',()=>{add({susp:-15,log:'Reviewer Shield drafted'});deck2()})}
function deck2(){stage(`<h2>Play your combo</h2><div class="meters">${meters()}</div>`);b('Cross + Assay + Figure','Resolve deck combo',()=>end('DECK COMBO RESOLVED','This loop works if card synergy feels collectible.'))}
function roulette(){stage(`<div class="kicker">Reviewer Roulette</div><h2>Submit before knowing the attack</h2><p class="body">Pick your risk level.</p>`);b('Safe claim','Lower payout, low roulette risk',()=>{add({cred:25,hype:-5,susp:-10});end('SAFE ACCEPT','You survived because the claim was boring.')});b('Medium claim','Balanced roulette',()=>{add({hype:20,weird:20,susp:15});end(Math.random()>.35?'LUCKY ACCEPT':'PAINFUL REVISION','Roulette creates tension but may feel arbitrary.')});b('Absurd claim','Huge payout, huge roulette risk',()=>{add({hype:50,weird:40,susp:45});end(Math.random()>.65?'LEGENDARY REVIEW':'INSTANT REJECTION','The thrill is whether Reviewer #2 catches you.')},'choice danger')}
function automation(){stage(`<div class="kicker">Lab Automation</div><h2>Build the experiment pipeline</h2>`);b('Add auto-sorter','Evidence +20, Time saved',()=>{add({ev:20,time:25,log:'Sorter removes manual bottleneck'});automation2()});b('Add assay scheduler','Hype +10, Evidence +15',()=>{add({ev:15,hype:10,log:'Assays batched overnight'});automation2()});b('Add figure script','Cred +10, Susp +10',()=>{add({cred:10,susp:10,log:'Script makes beautiful figures'});automation2()})}
function automation2(){end('PIPELINE ONLINE','Fun depends on seeing bottlenecks disappear and numbers accelerate.')}
function email(){stage(`<div class="kicker">PI Email Simulator</div><h2>Inbox: 7 unread disasters</h2>`);b('Reply to PI first','PI calms down, Time -20',()=>{add({cred:10,time:-20,log:'PI temporarily satisfied'});email2()});b('Reply to reviewer first','Cred +20, PI patience risk',()=>{add({cred:20,susp:-10,log:'Reviewer response drafted'});email2()});b('Ignore inbox and run assay','Evidence +25, Susp +20',()=>{add({ev:25,susp:20,log:'Inbox burns while data improves'});email2()})}
function email2(){end('INBOX TRIAGED','The writing is funny, but this loop may lack visual payoff unless paired with lab events.')}
function arcade(){stage(`<div class="kicker">Assay Arcade</div><h2>Time the blue-light pulse</h2><p class="body">Hit the target window for cleaner behavior traces.</p>`);b('Early pulse','Fast but noisy',()=>{add({ev:10,weird:20,susp:15});end('NOISY TRACE','Arcade needs real timing input to shine.')});b('Perfect pulse','Clean data',()=>{add({ev:35,cred:25,hype:10});end('CLEAN TRACE','A skill-based assay could add hands-on fun.')});b('Late pulse','Funny failure',()=>{add({weird:30,hype:10,susp:20});end('CHAOTIC TRACE','Failure is visually funny but less strategic.')})}
function claim(){stage(`<div class="kicker">Claim Tuning</div><h2>Set the claim strength</h2><p class="body">Too weak is boring. Too strong triggers scandal.</p>`);b('Careful: locomotor modulation','Cred +35, Hype -10',()=>{add({cred:35,hype:-10});end('BORING BUT SAFE','The safe claim works but may not be memorable.')});b('Bold: collective decision-making','Hype +35, Weird +20, Susp +20',()=>{add({hype:35,weird:20,susp:20});end('MEMORABLE CLAIM','This may be the cleanest core of the game.')});b('Absurd: fly hive mind','Hype +60, Susp +55',()=>{add({hype:60,weird:40,susp:55});end('SCANDAL BAIT','The upper edge is funny but needs consequence.')},'choice danger')}
function draw(){const c=$('#viz'),x=c.getContext('2d');let t=0;function f(){t+=.03;x.fillStyle='#02040a';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#26324a';x.strokeRect(8,8,c.width-16,c.height-16);x.fillStyle='rgba(90,150,255,.18)';x.fillRect(c.width*.38,20,c.width*.24,c.height-40);for(let i=0;i<34;i++){let a=t*2+i*.6,r=45+(i%8)*12,px=c.width/2+Math.cos(a+i)*r,py=c.height/2+Math.sin(a*1.2+i)*r*.55;x.fillStyle=i%5?'#f1d35e':'#72bdff';x.fillRect(px,py,7,7)}x.fillStyle='#d8e6ff';x.font='15px system-ui';x.fillText(loop.name,18,c.height-20);requestAnimationFrame(f)}f()}init();
