const $=s=>document.querySelector(s);let loops=[],sortMode=false;
const keys=['curiosity','tension','payoff','replay','feasible','present','fit'];
let state=JSON.parse(localStorage.ideaScores||'{}');
function save(){localStorage.ideaScores=JSON.stringify(state)}
function rec(id){return state[id]||(state[id]={fav:false,notes:'',scores:{}})}
function total(id){let r=rec(id);return keys.reduce((a,k)=>a+(+r.scores[k]||0),0)}
function render(){let q=($('#filter').value||'').toLowerCase();let arr=loops.filter(l=>JSON.stringify(l).toLowerCase().includes(q));if(sortMode)arr.sort((a,b)=>total(b.id)-total(a.id));$('#summary').textContent=`Showing ${arr.length}/200\nFavorites: ${loops.filter(l=>rec(l.id).fav).length}\nScored: ${loops.filter(l=>total(l.id)>0).length}\nTop by score:\n`+loops.slice().sort((a,b)=>total(b.id)-total(a.id)).slice(0,10).map(l=>`${String(l.n).padStart(3,'0')} ${total(l.id)} ${rec(l.id).fav?'★':''} ${l.name}`).join('\n');$('#list').innerHTML='';arr.forEach(l=>$('#list').appendChild(row(l)))}
function row(l){let r=rec(l.id);let d=document.createElement('div');d.className='row';d.innerHTML=`<button class="fav ${r.fav?'on':''}">${r.fav?'★':'☆'}</button><div><div class="kicker">#${String(l.n).padStart(3,'0')} · ${l.genre}</div><h2>${l.name}</h2><p>${l.hook}</p><p class="small"><b>Promise:</b> ${l.player_promise}</p><p class="small"><b>Cut:</b> ${l.cut_risk}</p><div class="actions"><a target="_blank" href="idea.html?id=${l.id}">Play</a><button class="copy">Copy pitch</button></div></div><div><div class="scoregrid">${keys.map(k=>`<label>${k}<input min="0" max="5" type="number" value="${r.scores[k]||''}" data-k="${k}"></label>`).join('')}</div><textarea placeholder="notes" style="margin-top:8px;width:100%;height:72px;background:#070b12;color:#fff;border:1px solid #384057;border-radius:8px;padding:8px">${r.notes||''}</textarea><p class="small">Total: <b>${total(l.id)}</b></p></div>`;d.querySelector('.fav').onclick=()=>{rec(l.id).fav=!rec(l.id).fav;save();render()};d.querySelectorAll('input').forEach(i=>i.oninput=()=>{rec(l.id).scores[i.dataset.k]=i.value;save();render()});d.querySelector('textarea').oninput=e=>{rec(l.id).notes=e.target.value;save()};d.querySelector('.copy').onclick=()=>navigator.clipboard?.writeText(`${l.name}\n${l.thirty_second_pitch}\n${l.player_promise}`);return d}
$('#filter').oninput=render;$('#sort').onclick=()=>{sortMode=!sortMode;render()};$('#export').onclick=()=>{let selected=loops.filter(l=>rec(l.id).fav||total(l.id)>0).map(l=>({id:l.id,n:l.n,name:l.name,total:total(l.id),fav:rec(l.id).fav,scores:rec(l.id).scores,notes:rec(l.id).notes,pitch:l.thirty_second_pitch}));let blob=new Blob([JSON.stringify(selected,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='idea-shortlist.json';a.click()};
fetch('loops200.json?v=distinct-200-v2').then(r=>r.json()).then(d=>{loops=d;render()});